[package]
name = "plotters-imgui"
version = "0.1.0"
authors = ["Moritz Drexl <mdrexl@fastmail.fm>"]
edition = "2018"

[dependencies]
plotters-backend = "^0.3.*"
imgui = "0.8"
earcutr = { git = "https://github.com/donbright/earcutr", rev = "aaa18bfdfe581db26bb9869aec170329b4e14f4c" }
